// template-react/src/App.tsx
import style from './App.module.css';
import { useState } from 'react';

function App() {
    const [count, setCount] = useState(0);

    return (
        <button className={style.button} onClick={() => setCount(prev => prev + 1)}>
            {count}
        </button>
    );
}

export default App;

// template-solid/src/App.tsx
import style from './App.module.css';
import { createSignal } from 'solid-js';

function App() {
    const [getCount, setCount] = createSignal(0);

    return (
        <button class={style.button} onClick={() => setCount(prev => prev + 1)}>
            {getCount()}
        </button>
    );
}

export default App;
