// template-solid/src/App.tsx
import style from './App.module.css';
import { createSignal } from 'solid-js';

function App() {
    const [getCount, setCount] = createSignal(0);

    return (
        <button class={style.button} onClick={() => setCount(prev => prev + 1)}>
            {getCount()}
        </button>
    );
}

export default App;

// template-next/src/app/page.tsx
'use client';

import React from 'react';
import css from './page.module.css';

function App() {
    const [count, setCount] = React.useState(0);

    return (
        <button className={css.button} onClick={() => setCount(count + 1)}>
            {count}
        </button>
    );
}

export default App;
